module.exports = {
 root: true,
 parser: 'babel-eslint',
 parserOptions: {
   ecmaVersion: 2017,
   sourceType: 'module',
   ecmaFeatures: {jsx: true}
 },
 env: {browser: true, node: true, es6: true, mocha: true},
 extends: [
   'eslint:recommended',
   'plugin:react/recommended',
   'prettier',
   'plugin:import/errors',
   'plugin:import/warnings',
   'plugin:ramda/recommended',
   'plugin:unicorn/recommended',
   'plugin:sonarjs/recommended'
 ],
 settings: {react: {version: '16.6'}},
 plugins: [
   'sonarjs',
   'react',
   'prettier',
   'fp',
   'immutable',
   'ramda',
   'unicorn'
 ],
 rules: {
   'fp/no-arguments': 'error',
   'fp/no-delete': 'error',
   'fp/no-events': 'error',
   'fp/no-get-set': 'error',
   'fp/no-proxy': 'error',
   'fp/no-valueof-field': 'error',
   'prefer-const': 'error',
   'prefer-arrow-callback': 'error',
   'no-var': 'error',
   'no-bitwise': 'error',
   'jsx-quotes': ['error', 'prefer-double'],
   'func-style': 'error',
   camelcase: 'error',
   'no-octal-escape': 'error',
   'no-implicit-globals': 'error',
   'no-fallthrough': 'off',
   'no-extend-native': 'error',
   'no-eval': 'error',
   'no-empty-function': 'error',
   'no-caller': 'error',
   'no-alert': 'error',
   'no-use-before-define': ['error', {functions: true, classes: true}],
   eqeqeq: 'off',
   'block-scoped-var': 'error',
   'react/display-name': 'off',
   'react/prop-types': 'off',
   'no-unused-vars': 'error',
   'require-yield': 'off',
   'no-duplicate-imports': 'error',
   'dot-notation': 'error',
   'quote-props': ['error', 'as-needed'],
   'arrow-body-style': ['error', 'as-needed'],
   'object-shorthand': 'error',
   'prettier/prettier': ['error', {singleQuote: true, bracketSpacing: false}],
   'immutable/no-let': 'error',
   'immutable/no-this': 'error',
   'immutable/no-mutation': 'error',
 }
};